class AppConstants {
  static const termsOfServiceUrl = 'https://www.apheleia.me/legal';
  static const privacyPolicyUrl = 'https://www.apheleia.me/legal';
  static const discordUrl = 'https://discord.com/invite/Yu45Qddb';

  static const newsSourceList = [
    "24/7 Wall Street",
    "Accesswire",
    "Barrons",
    "Benzinga",
    "Business Insider",
    "Business Wire",
    "CNBC",
    "CNBC International TV",
    "CNBC Television",
    "CNET",
    "CNN",
    "CNN Business",
    "Cheddar",
    "Deadline",
    "Discount The Obvious",
    "ETF Trends",
    "ETFcom",
    "Fast Company",
    "Forbes",
    "Fox Business",
    "FreightWaves",
    "GeekWire",
    "GlobeNewsWire",
    "GuruFocus",
    "Huffington Post",
    "Investopedia",
    "InvestorPlace",
    "Investors Business Daily",
    "Invezz",
    "Kiplinger",
    "Market Watch",
    "Morningstar",
    "NYTimes",
    "New York Post",
    "Newsfile Corp",
    "OTC PR Wire",
    "Proactive Investors",
    "PYMNTS",
    "PR Newswire",
    "Pulse2",
    "Reuters",
    "Schaeffers Research",
    "See It Market",
    "Seeking Alpha",
    "Skynews",
    "TechCrunch",
    "The Dog of Wall Street",
    "The Guardian",
    "The Motley Fool",
    "VentureBeat",
    "Zacks Investment Research",
  ];
}
